# Your Solution
 
 

 
services:
  # Book Catalog Service
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://week07_vxjq_user:t2vmpKNW1GoYanOBq3Uqfeb2zd7WZXtQ@dpg-crk4jh3tq21c73aai25g-a.oregon-postgres.render.com/week07_vxjq
 
  # Inventory Management Service
  inventory_management:
    image: inventory_management
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://week07_vxjq_user:t2vmpKNW1GoYanOBq3Uqfeb2zd7WZXtQ@dpg-crk4jh3tq21c73aai25g-a.oregon-postgres.render.com/week07_vxjq
 
